### add collection
POST http://localhost:8080//api/Collection
Content-Type: application/json

{
    "name": "collection1",
    "description": "description2",
    "creation_date": "2025-08-07",
    "modification_date": "2025-10-10",
    "still_updated": 1
}

### overwiew
GET http://localhost:8080/api/Overview

### list
GET http://localhost:8080/api/List

### info
GET http://localhost:8080/api/Info

### add Backup
POST http://localhost:8080/api/Backup
Content-Type: application/json

### Edit
POST http://localhost:8080/api/Edit
content-type: application/json

### Search specifik term
GET http://localhost:8080/api/Search?name=collection

### Search allt
GET http://localhost:8080/api/Search?name=

{
    "name": "collection",
    "backup_name": "backup1",
    "date": "2025-10-10",
    "location": "BTH"
}
